### ISSUE TITLE
Please add all the questions

### ISSUE THREAD

**Issue by abinashdash17** [kingkrab6666/UNIX#1]
I can't find the questions. Kindly add all the question to your GitHub repo.

**Comment by kingkrab6666** [comment]
Hello,
You can find every question and answer at exploreidea.net

**Comment by abinashdash17** [comment]
Oh. great... Thanks. I suggest you to add this link in a readme file so that others can find it easily without checking this issue.

**Comment by kingkrab6666** [comment]
I'll do that. Join my telegram for latest updates. Search @kingkrab6666
